[package]
name = "salieri"
description = "Amadeus services consumer"
version = "0.3.12"
edition = "2021"

[features]
default             = ["kafka", "gpt4free"]
kafka               = ["rdkafka", "futures", "async-recursion"]
gpt4free            = ["inline-python", "once_cell"]

[dependencies]
mozart          = { path = "../Mozart" }
serde           = { workspace = true }
anyhow          = { workspace = true }
celery          = { workspace = true }
tokio           = { workspace = true }
env_logger      = "0.10"
log             = "0.4.17"
futures         = {version = "0.3", optional = true}
async-recursion = { optional = true, workspace = true }
inline-python   = {version = "0.10", optional = true}
once_cell       = { optional = true, workspace = true }

[dependencies.rdkafka]
version = "0.31"
optional = true
features = ["dynamic-linking", "tokio"]
