[package]
name = "salieri"
description = "Amadeus services consumer"
version = "0.2.1"
edition = "2021"

[features]
default             = ["kafka"]
kafka               = ["rdkafka", "futures"]

[dependencies]
mozart      = { path = "../Mozart" }
serde       = "1"
env_logger  = "0.10"
log         = "0.4.17"
anyhow      = "1"
futures     = {version = "0.3", optional = true}

[dependencies.tokio]
version = "1.26.0"
features = ["rt-multi-thread", "signal", "parking_lot", "macros", "fs"]

[dependencies.rdkafka]
version = "0.29"
optional = true
features = ["dynamic-linking", "tokio"]

[dependencies.celery]
git = "https://github.com/rusty-celery/rusty-celery.git"
branch = "main"
