[package]
name = "salieri"
description = "Amadeus services consumer"
version = "0.1.8"
edition = "2021"

[dependencies]
mozart      = { path = "../Mozart" }
serde       = "1"
env_logger  = "0.10"
log         = "0.4.17"
anyhow      = "1"

[dependencies.tokio]
version = "1.25.0"
features = ["rt-multi-thread", "signal", "parking_lot", "macros", "fs"]

[dependencies.celery]
git = "https://github.com/Qeenon/rusty-celery.git"
branch = "mawa"
