parameters:
  name: ''
  vmImage: ''
  toolchain: 'nightly'
  features: 'trackers'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    tc: ${{ parameters.toolchain }}
    os: ${{ parameters.vmImage }}
    features: ${{ parameters.features }}
  steps:

  - bash: |
      if [[ "$OS" == "macOS-latest" ]]; then
        HOMEBREW_NO_AUTO_UPDATE=1 brew install automake autoconf libtool libsodium pkg-config
      fi
      if [[ "$OS" == "ubuntu-latest" ]]; then
        sudo apt-get update
        sudo apt-get install -y build-essential git
        sudo apt-get install -y libsodium-dev libssl-dev libopus-dev
        git clone --depth 1 --branch v1.9.2 https://github.com/edenhill/librdkafka.git
        cd librdkafka
        ./configure --prefix=/usr
        make -j$(nproc)
        sudo make install
      fi
    displayName: 'Install dependencies'

  - bash: |
      curl -o rustup-init.sh https://sh.rustup.rs -sSf
      sh rustup-init.sh --default-toolchain $(tc) -y
    displayName: 'Install Rust'

  - bash: |
      source $HOME/.cargo/env
      if [[ "$(features)" == "all" ]]; then
        cargo test --all-features
      else
        cargo test --no-default-features --features "$(features)"
      fi
    displayName: 'Test Amadeus'
