[workspace]
members = [
  "Mozart",
  "Amadeus",
  "Salieri"
]

[workspace.dependencies]
anyhow              = "^1"
async-recursion     = "^1"
once_cell           = "^1.17"
serde               = "^1"
tokio               = "^1.28.1"
celery              = "*"

[profile.release]
opt-level           = 3
overflow-checks     = false
debug-assertions    = false
lto                 = "thin"

[profile.fat-release]
inherits          = "release"
debug             = false
debug-assertions  = false
overflow-checks   = false
lto               = "fat"
