[package]
name                = "amadeus"
version             = "10.4.15"
authors             = [ "Miezhiko" ]
repository          = "https://github.com/Miezhiko/Amadeus"
readme              = "README.md"
keywords            = [ "discord", "bot" ]
edition             = "2021"
description         = "memory storage and artificial intelligence system"
license             = "AGPL-3.0-only"
rust-version        = "1.63.0"

[features]
default             = ["trackers", "torch"]
trackers            = []
torch               = []
spam_filter         = []
flo                 = ["tonic", "hex", "flo-grpc"]
voice_analysis      = ["dasp_interpolate", "dasp_signal", "deepspeech"]
full                = ["flo", "voice_analysis", "trackers"]

[dependencies]
mozart              = { path = "../Mozart" }
chrono              = "0.4.24"
glob                = "0.3.1"
chrono-tz           = "0.8.1"
tracing             = "0.1.37"
tracing-log         = "0.1.3"
tracing-subscriber  = "0.3.16"
regex               = "1.7.1"
serde               = "1.0.158"
serde_derive        = "1.0.158"
serde_json          = "1.0.94"
serde_yaml          = "0.9.19"
once_cell           = "1.17.1"
ucd                 = "0.1.1"
comfy-table         = "6.1.4"
async-std           = "1.12"
futures-util        = "0.3.27"
qrcode              = "0.12"
cannyls             = "0.10"
bincode             = "2.0.0-rc.2"
itertools           = "0.10.5"
anyhow              = "1"
async-recursion     = "1.0.4"
unic-langid         = "0.9.1"
fluent-templates    = "0.8"
sled                = "0.34.7"
kathoey             = "1.1.4"
serde_dhall         = "0.12.1"
nipper              = "0.1.9"
plotters            = "0.3.4"

cynic   = { version = "2.2.8",    features = ["http-reqwest"] }
rand    = { version = "0.8.5",    features = ["std", "std_rng"] }
reqwest = { version = "0.11.15",  features = ["json", "blocking"] }
ical    = { version = "0.8",      features = ["ical"] }
markov  = { version = "1.1",      features = ["yaml"] }

[dependencies.stroke]
git = "https://github.com/dorianprill/stroke.git"
branch = "main"

[dependencies.songbird]
default-features = false
git = "https://github.com/FelixMcFelix/songbird.git"
branch = "symphonia"
features = [ "serenity-rustls"
           , "driver"
           , "gateway"
           , "serenity-deps"
           ]

[dependencies.serenity]
default-features = false
git = "https://github.com/serenity-rs/serenity"
branch = "next"
features = [ "cache"
           , "builder"
           , "model"
           , "framework"
           , "standard_framework"
           , "voice"
           , "client"
           , "http"
           , "native_tls_backend"
           , "utils"
           , "collector"
           , "unstable_discord_api"
           , "chrono"
           , "gateway"
           , "tokio_task_builder"
           ]

[dependencies.hex]
version = "0.4.3"
optional = true

# follow version on flo
# https://github.com/w3champions/flo/blob/develop/crates/client/Cargo.toml
[dependencies.tonic]
version = "0.6"
optional = true

[dependencies.flo-grpc]
git = "https://github.com/w3champions/flo-grpc.git"
branch = "main"
optional = true

[dependencies.tokio]
version = "1.26.0"
features = ["rt-multi-thread", "signal", "parking_lot", "macros", "fs"]

[dependencies.dasp_signal]
version = "0.11"
optional = true

[dependencies.dasp_interpolate]
version = "0.11"
optional = true
features = ["linear"]

[dependencies.deepspeech]
version = "0.9.1"
optional = true

[dependencies.celery]
git = "https://github.com/rusty-celery/rusty-celery.git"
branch = "main"
